#!/usr/bin/env bash
# Configures Nginx to run as nginx and listen on port 8080

pkill nginx || true
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
chown -R nginx:nginx /var/log/nginx
chown -R nginx:nginx /var/lib/nginx
touch /run/nginx.pid
chown nginx:nginx /run/nginx.pid
sudo -u nginx /usr/sbin/nginx
