#!/usr/bin/env bash
# Configures UFW to deny incoming traffic except SSH, HTTP and HTTPS

apt-get update
apt-get install -y ufw

ufw default deny incoming
ufw default allow outgoing

ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp

ufw --force enable
