#!/usr/bin/env bash
# Installs Nginx and adds an X-Served-By response header

apt-get update
apt-get install -y nginx
echo "Holberton School for the win!" > /var/www/html/index.html
sed -i '/server_name _;/a \        add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
service nginx restart
