#!/usr/bin/env bash
# Installs Nginx and adds an X-Served-By response header

apt-get update
apt-get install -y nginx

server_hostname="$(hostname)"
echo "Holberton School for the win!" > /var/www/html/index.html

sed -i "/server_name _;/a \\\tadd_header X-Served-By ${server_hostname};" /etc/nginx/sites-available/default

nginx -t
service nginx restart
