#!/usr/bin/env bash
# Installs Nginx and configures a permanent HTTP redirect

apt-get update
apt-get install -y nginx
echo "Holberton School for the win!" > /var/www/html/index.html

sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

nginx -t
service nginx restart
